#
# GitHub Actions Workflow for pull request events against main
# check for problems in links.

name: Check links
on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '23 8 * * 1'
  workflow_dispatch:

jobs:
  check_links:
    name: Check Markdown links  # TODO: Check also Asciidoc (this should take place in https://github.com/cf-convention/cf-conventions)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@v1.0.4
        
      - name: Upload report
        if: ${{ always() }}
        uses: actions/upload-artifact@v1
        with:
          name: Link check report
          path: ./lychee/out.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      
      - name: Create Issue From File
        if: env.lychee_exit_code != 0  # Only execute if check failed
        uses: peter-evans/create-issue-from-file@v4.0.0
        
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
